=== printer83mph/cis7000-pipeline/asset-schema-v1.3.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CIS-7000 Asset Metadata v1.3.0",
  "description": "An asset's metadata for use in CIS-7000 Production Pipeline, SP2024",
  "properties": {
    "assetName": {
      "description": "The asset's name, in camelCase",
      "type": "string"
    },
    "author": {
      "description": "The original asset author's Pennkey",
      "type": "string"
    },
    "historical": {
      "description": "All historical modifications to this asset, including the original author's creation.\nIn chronological order, with the most recent modification first.",
      "type": "array",
      "items": {
        "type": "object",
        "description": "A modification to this asset",
        "properties": {
          "author": {
            "type": "string",
            "description": "The Pennkey of the author of this modification"
          },
          "date": {
            "description": "The date of this modification",
            "type": "string",
            "format": "date"
          },
          "changes": {
            "description": "A brief description of the changes made in this modification",
            "type": "string"
          }
        },
        "required": ["author", "date", "changes"]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "version": {
      "description": "Major and minor version of this asset, i.e. 1.0",
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+$"
    },
    "keywords": {
      "description": "Key words or phrases associated with this asset",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
    "assetName",
    "author",
    "historical",
    "version"
  ]
}

=== printer83mph/cis7000-pipeline/kitchenaid/metadata.json
{
  "assetName": "kitchenaid",
  "author": "tlshaw",
  "version": "1.2",
  "historical": [
    {
      "author": "tlshaw",
      "date": "2024-02-05",
      "changes": "Initial version"
    }
  ],
  "keywords": [
    "mixer",
    "kitchenaid",
    "stand mixer",
    "kitchen",
    "appliance"
  ]
}
